import type { StreamDockModelDefinition } from './list.js'

export const K1ProDefinition: StreamDockModelDefinition = {
	productName: 'Stream Dock K1 Pro',
	iconRotation: -90,
	reportId: 0x04,
	// StreamDock leaves the final byte of every 1025-byte HID image report as zero:
	// report ID (1) + JPEG data (1023) + trailing zero (1).
	imagePacketDataSize: 1023,
	hidInterface: 1,
	hidUsagePage: 65440,
	hidUsage: 1,
	disableWebModeOnConnect: true,
	usbIds: [
		{
			vendorId: 0x5548,
			productIds: [0x1025],
		},
		{
			vendorId: 0x6603,
			productIds: [0x1020],
		},
		{
			vendorId: 0x6603,
			productIds: [0x1015],
		},
	],

	inputs: [
		{
			type: 'button',
			id: 0x25,
			row: 0,
			column: 0,
			name: 'Rotary encoder 1',
		},
		{
			type: 'rotateLeft',
			id: 0x50,
			row: 0,
			column: 0,
			name: 'Rotary encoder 1',
		},
		{
			type: 'rotateRight',
			id: 0x51,
			row: 0,
			column: 0,
			name: 'Rotary encoder 1',
		},
		{
			type: 'button',
			id: 0x30,
			row: 0,
			column: 1,
			name: 'Rotary encoder 2',
		},
		{
			type: 'rotateLeft',
			id: 0x60,
			row: 0,
			column: 1,
			name: 'Rotary encoder 2',
		},
		{
			type: 'rotateRight',
			id: 0x61,
			row: 0,
			column: 1,
			name: 'Rotary encoder 2',
		},
		{
			type: 'button',
			id: 0x31,
			row: 0,
			column: 2,
			name: 'Rotary encoder 3',
		},
		{
			type: 'rotateLeft',
			id: 0x90,
			row: 0,
			column: 2,
			name: 'Rotary encoder 3',
		},
		{
			type: 'rotateRight',
			id: 0x91,
			row: 0,
			column: 2,
			name: 'Rotary encoder 3',
		},
		{
			type: 'button',
			id: 0x05,
			row: 1,
			column: 0,
			name: 'Button 1',
		},
		{
			type: 'button',
			id: 0x03,
			row: 1,
			column: 1,
			name: 'Button 2',
		},
		{
			type: 'button',
			id: 0x01,
			row: 1,
			column: 2,
			name: 'Button 3',
		},
		{
			type: 'button',
			id: 0x06,
			row: 2,
			column: 0,
			name: 'Button 4',
		},
		{
			type: 'button',
			id: 0x04,
			row: 2,
			column: 1,
			name: 'Button 5',
		},
		{
			type: 'button',
			id: 0x02,
			row: 2,
			column: 2,
			name: 'Button 6',
		},
	],
	outputs: [
		{
			type: 'lcd',
			id: 0x05,
			row: 1,
			column: 0,
			name: 'LCD 4',
			resolutionx: 64,
			resolutiony: 64,
		},
		{
			type: 'lcd',
			id: 0x03,
			row: 1,
			column: 1,
			name: 'LCD 5',
			resolutionx: 64,
			resolutiony: 64,
		},
		{
			type: 'lcd',
			id: 0x01,
			row: 1,
			column: 2,
			name: 'LCD 6',
			resolutionx: 64,
			resolutiony: 64,
		},
		{
			type: 'lcd',
			id: 0x06,
			row: 2,
			column: 0,
			name: 'LCD 7',
			resolutionx: 64,
			resolutiony: 64,
		},
		{
			type: 'lcd',
			id: 0x04,
			row: 2,
			column: 1,
			name: 'LCD 8',
			resolutionx: 64,
			resolutiony: 64,
		},
		{
			type: 'lcd',
			id: 0x02,
			row: 2,
			column: 2,
			name: 'LCD 9',
			resolutionx: 64,
			resolutiony: 64,
		},
	],
}
