import type { StreamDockModelDefinition } from './list.js'

export const N1Definition: StreamDockModelDefinition = {
	productName: 'Stream Dock N1',
	iconRotation: 0,
	// The N1 has three modes (calculator, numpad, console) toggled via the rotary encoder.
	// Only console mode (0x33) renders images sent by the software, so switch into it on connect.
	initialMode: 0x33,
	// N1 reports ACK/OK AA FF after switching into console mode. The switch clears
	// the LCDs, so this report triggers restoration of Companion's cached images.
	modeReport: 0xaa,
	modeReportValue: 0xff,
	usbIds: [
		{
			vendorId: 0x6603,
			productIds: [0x1011],
		},
	],

	inputs: [
		{
			type: 'button',
			id: 0x1e,
			row: 0,
			column: 0,
			name: 'Button 1',
		},
		{
			type: 'button',
			id: 0x1f,
			row: 0,
			column: 1,
			name: 'Button 2',
		},
		{
			type: 'button',
			id: 0x23,
			row: 0,
			column: 2,
			name: 'Rotary encoder 1',
		},
		{
			type: 'rotateLeft',
			id: 0x32,
			row: 0,
			column: 2,
			name: 'Rotary encoder 1',
		},
		{
			type: 'rotateRight',
			id: 0x33,
			row: 0,
			column: 2,
			name: 'Rotary encoder 1',
		},
		{
			type: 'button',
			id: 0x01,
			row: 1,
			column: 0,
			name: 'Button 3',
		},
		{
			type: 'button',
			id: 0x02,
			row: 1,
			column: 1,
			name: 'Button 4',
		},
		{
			type: 'button',
			id: 0x03,
			row: 1,
			column: 2,
			name: 'Button 5',
		},
		{
			type: 'button',
			id: 0x04,
			row: 2,
			column: 0,
			name: 'Button 6',
		},
		{
			type: 'button',
			id: 0x05,
			row: 2,
			column: 1,
			name: 'Button 7',
		},
		{
			type: 'button',
			id: 0x06,
			row: 2,
			column: 2,
			name: 'Button 8',
		},
		{
			type: 'button',
			id: 0x07,
			row: 3,
			column: 0,
			name: 'Button 9',
		},
		{
			type: 'button',
			id: 0x08,
			row: 3,
			column: 1,
			name: 'Button 10',
		},
		{
			type: 'button',
			id: 0x09,
			row: 3,
			column: 2,
			name: 'Button 11',
		},
		{
			type: 'button',
			id: 0x0a,
			row: 4,
			column: 0,
			name: 'Button 12',
		},
		{
			type: 'button',
			id: 0x0b,
			row: 4,
			column: 1,
			name: 'Button 13',
		},
		{
			type: 'button',
			id: 0x0c,
			row: 4,
			column: 2,
			name: 'Button 14',
		},
		{
			type: 'button',
			id: 0x0d,
			row: 5,
			column: 0,
			name: 'Button 15',
		},
		{
			type: 'button',
			id: 0x0e,
			row: 5,
			column: 1,
			name: 'Button 16',
		},
		{
			type: 'button',
			id: 0x0f,
			row: 5,
			column: 2,
			name: 'Button 17',
		},
	],
	outputs: [
		{
			type: 'lcd',
			id: 0x10,
			row: 0,
			column: 0,
			name: 'LCD 1',
			resolutionx: 80,
			resolutiony: 80,
		},
		{
			type: 'lcd',
			id: 0x11,
			row: 0,
			column: 1,
			name: 'LCD 2',
			resolutionx: 80,
			resolutiony: 80,
		},
		{
			type: 'lcd',
			id: 0x12,
			row: 0,
			column: 2,
			name: 'LCD 3',
			resolutionx: 80,
			resolutiony: 80,
		},
		{
			type: 'lcd',
			id: 0x01,
			row: 1,
			column: 0,
			name: 'LCD 4',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x02,
			row: 1,
			column: 1,
			name: 'LCD 5',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x03,
			row: 1,
			column: 2,
			name: 'LCD 6',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x04,
			row: 2,
			column: 0,
			name: 'LCD 7',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x05,
			row: 2,
			column: 1,
			name: 'LCD 8',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x06,
			row: 2,
			column: 2,
			name: 'LCD 9',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x07,
			row: 3,
			column: 0,
			name: 'LCD 10',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x08,
			row: 3,
			column: 1,
			name: 'LCD 11',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x09,
			row: 3,
			column: 2,
			name: 'LCD 12',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x0a,
			row: 4,
			column: 0,
			name: 'LCD 13',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x0b,
			row: 4,
			column: 1,
			name: 'LCD 14',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x0c,
			row: 4,
			column: 2,
			name: 'LCD 15',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x0d,
			row: 5,
			column: 0,
			name: 'LCD 16',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x0e,
			row: 5,
			column: 1,
			name: 'LCD 17',
			resolutionx: 96,
			resolutiony: 96,
		},
		{
			type: 'lcd',
			id: 0x0f,
			row: 5,
			column: 2,
			name: 'LCD 18',
			resolutionx: 96,
			resolutiony: 96,
		},
	],
}
